[package]
name = "valuecore"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
num-bigint = "0.4"
num-traits = "0.2"
serde_json = "1"
sha2 = "0.10"

[dev-dependencies]
pretty_assertions = "1"
