[package]
name = "fardlang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21"
serde_json = "1"

valuecore = { path = "../valuecore" }

[[test]]
name = "match_parse_smoke"
path = "tests/match_parse_smoke.rs"
