[package]
name = "fardc"
version = "0.1.0"
edition = "2021"

[dependencies]
fardlang = { path = "../fardlang" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
valuecore = { path = "../valuecore" }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"
