[package]
name = "fard"
version = "0.1.0"
edition = "2021"

[dependencies]
fardlang = { path = "../fardlang" }
valuecore = { path = "../valuecore" }
ureq = "2"
rand = "0.8"
serde_json = "1"
anyhow = "1"
