[package]
name = "witnesscore"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
valuecore = { path = "../valuecore" }

[dev-dependencies]
pretty_assertions = "1"
num-bigint = "0.4"
